# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
# ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
ENABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_RUFF
  - CSS_STYLELINT
  - HTML_HTMLHINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
MARKDOWN_FILTER_REGEX_EXCLUDE: '(LICENSE\.md|docs/NEWS\.md)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
PRE_COMMANDS:
  - command: R --slave -e 'install.packages(c("lintr"))'
    cwd: "root"
PRINT_ALL_FILES: false